image:
  file: .gitpod.Dockerfile

additionalRepositories:
  - url: https://github.com/dwarakaprasad/generator-jhipster.git

tasks:
  - name: setup_jhipster
    before: |
      cd ../generator-jhipster
    init: |
      npm install
    command: |
      npm link
    
  - name: setup_workarea
    command: |
